// Configuração central dos operadores, variantes de filtro e opções de ordenação das tabelas.
export type DataTableConfig = typeof dataTableConfig;

export const dataTableConfig = {
  textOperators: [
    { label: "Contém", value: "iLike" as const },
    { label: "Não contém", value: "notILike" as const },
    { label: "É", value: "eq" as const },
    { label: "Não é", value: "ne" as const },
    { label: "Está vazio", value: "isEmpty" as const },
    { label: "Não está vazio", value: "isNotEmpty" as const },
  ],
  numericOperators: [
    { label: "É", value: "eq" as const },
    { label: "Não é", value: "ne" as const },
    { label: "Menor que", value: "lt" as const },
    { label: "Menor ou igual a", value: "lte" as const },
    { label: "Maior que", value: "gt" as const },
    { label: "Maior ou igual a", value: "gte" as const },
    { label: "Está entre", value: "isBetween" as const },
    { label: "Está vazio", value: "isEmpty" as const },
    { label: "Não está vazio", value: "isNotEmpty" as const },
  ],
  dateOperators: [
    { label: "Is", value: "eq" as const },
    { label: "Is not", value: "ne" as const },
    { label: "Is before", value: "lt" as const },
    { label: "Is after", value: "gt" as const },
    { label: "Is on or before", value: "lte" as const },
    { label: "Is on or after", value: "gte" as const },
    { label: "Is between", value: "isBetween" as const },
    { label: "Is relative to today", value: "isRelativeToToday" as const },
    { label: "Is empty", value: "isEmpty" as const },
    { label: "Is not empty", value: "isNotEmpty" as const },
  ],
  selectOperators: [
    { label: "É", value: "eq" as const },
    { label: "Não é", value: "ne" as const },
    { label: "Está vazio", value: "isEmpty" as const },
    { label: "Não está vazio", value: "isNotEmpty" as const },
  ],
  multiSelectOperators: [
    { label: "Contém qualquer um", value: "inArray" as const },
    { label: "Não contém nenhum", value: "notInArray" as const },
    { label: "Está vazio", value: "isEmpty" as const },
    { label: "Não está vazio", value: "isNotEmpty" as const },
  ],
  booleanOperators: [
    { label: "É", value: "eq" as const },
    { label: "Não é", value: "ne" as const },
  ],
  sortOrders: [
    { label: "Crescente", value: "asc" as const },
    { label: "Decrescente", value: "desc" as const },
  ],
  filterVariants: [
    "text",
    "number",
    "range",
    "date",
    "dateRange",
    "boolean",
    "select",
    "multiSelect",
  ] as const,
  operators: [
    "iLike",
    "notILike",
    "eq",
    "ne",
    "inArray",
    "notInArray",
    "isEmpty",
    "isNotEmpty",
    "lt",
    "lte",
    "gt",
    "gte",
    "isBetween",
    "isRelativeToToday",
  ] as const,
  joinOperators: ["and", "or"] as const,
};
